spring:
  datasource:
    url: jdbc:h2:mem:skyblock_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
config:
  hypixel:
    api-url: https://api.hypixel.net/v2
  NEU:
    repo-url: https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO
